[package]
name = "vec_stubs"
version = "0.1.0"
authors = ["Zach Shipko <zachshipko@gmail.com>"]

[lib]
crate-type = ["staticlib", "cdylib"]

[dependencies]
ocaml = {git = "https://github.com/zshipko/ocaml-rs"}
